### ISSUE TITLE
question

### ISSUE THREAD

**Issue by fukemy** [radams15/asterisk-docker#1]
Hi there, thanks you for working hard on Docker + Asterisk. I am trying to research everywhere to finding my solution about SIP trunk and Pjsip Register. Can you help me to know about this:

 My question is:
  1. If I run with `--net=host`, I can make my SIP trunk connected, but my `pjsip endpoints` can not be registered
  2. If I run with expose port only: `-p 5060:5060/udp ....`, I can register my `pjsip endpoints` but the trunk is UNREACHABLE.

**Comment by radams15** [comment]
Whilst this is not directly related to my project, the only thing I can think of is that you might have not set your IPs correctly in pjsip.conf:

```
external_media_address=[EXTERNAL_IP]
external_signaling_address=[EXTERNAL_IP]
local_net=127.0.0.0/12
local_net=[INTERNAL_IP]
```

Where INTERNAL_IP is the subnet mask of your internal network, i.e. 10.0.0.0/24 or 192.168.0.1/24. This works best with `--net=host`.

Also ensure that `bind` is set to `0.0.0.0:5060` and not any local IP as this could interfere with registration.


Hope this helps,

Rhys.
